"""Static-file HTTP server for the trade dashboard.

Serves ~/.trade/ as the document root, so /dashboard/index.html and
/media/<date>/<uid>.jpg both resolve naturally from the index.html
generated by trade.dashboard.

Two optional gates:
  - URL token: TRADE_DASHBOARD_TOKEN — requests must include /<token>/...
    as the path prefix; the token is stripped before file resolution.
  - HTTP Basic Auth: TRADE_DASHBOARD_USER + TRADE_DASHBOARD_PASSWORD.

Both empty = server is open. Pick at least Basic Auth if exposing the
port on the public internet.

Usage:
    python -m trade.dashboard_server [--port 8082] [--bind 0.0.0.0]
"""

import argparse
import base64
import gzip
import http.server
import json
import logging
import os
import re
import shutil
import socketserver
import sys
import time
from functools import partial
from io import BytesIO
from pathlib import Path

from dotenv import load_dotenv

from trade.dashboard import _alert_to_payload as _payload_for_api
from trade.store import latest_per_dedup_key, list_all_alerts, open_db, stats

load_dotenv()

_TOKEN = (os.environ.get("TRADE_DASHBOARD_TOKEN") or "").strip()
_AUTH_USER = (os.environ.get("TRADE_DASHBOARD_USER") or "").strip()
_AUTH_PASSWORD = (os.environ.get("TRADE_DASHBOARD_PASSWORD") or "").strip()
_DATA_DIR = Path(os.environ.get("TRADE_DATA_DIR") or Path.home() / ".trade")


def _public_share_token() -> str:
    """공개 export용 랜덤 토큰. 환경변수 우선, 없으면 파일에 영구 저장된 값
    재사용(없으면 신규 생성). 외부에 공개되는 단 하나의 경로 prefix."""
    env = (os.environ.get("TRADE_DASHBOARD_PUBLIC_TOKEN") or "").strip()
    if env:
        return env
    f = _DATA_DIR / ".public_token"
    try:
        v = f.read_text().strip()
        if v:
            return v
    except OSError:
        pass
    import secrets
    v = secrets.token_urlsafe(24)
    try:
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(v)
    except OSError:
        pass
    return v


_PUBLIC_TOKEN = _public_share_token()
# 공개 prefix(=토큰을 모르면 못 들어옴). 그 안에서도 월별 스냅샷
# 'YYYY-MM.html'만 서빙 — 라이브 대쉬보드/다른 파일은 절대 노출 안 됨.
_PUBLIC_PREFIX = f"/share/{_PUBLIC_TOKEN}/"
_SHARE_FILE_RE = re.compile(r"^\d{4}-\d{2}\.html$")
_STORE_PATH = _DATA_DIR / "store.db"
_INBOX_PATH = _DATA_DIR / "inbox.jsonl"
_DASHBOARD_HTML = _DATA_DIR / "dashboard" / "index.html"

# Compress text responses larger than this. JPEG/PNG already
# pre-compressed; gzipping again wastes CPU for no win.
_GZIP_MIN_BYTES = 1024
_GZIP_MIME_PREFIXES = (
    "text/", "application/json", "application/javascript",
)

log = logging.getLogger("trade-dashboard")


# ---------------------------------------------------------------------
# gzip helpers
# ---------------------------------------------------------------------

class _CapturingWFile:
    """File-like that buffers everything the SimpleHTTPRequestHandler
    writes (headers + body), so we can inspect Content-Type and gzip
    eligible MIME types after the handler finishes.
    """

    def __init__(self) -> None:
        self._buf = BytesIO()

    def write(self, data: bytes) -> int:
        return self._buf.write(data)

    def flush(self) -> None:
        pass

    def split(self) -> tuple[bytes, bytes]:
        """Returns (header_bytes_with_crlf, body_bytes)."""
        raw = self._buf.getvalue()
        sep = raw.find(b"\r\n\r\n")
        if sep == -1:
            return raw, b""
        return raw[: sep + 4], raw[sep + 4 :]


def _pick_content_type(header_bytes: bytes) -> str | None:
    for line in header_bytes.split(b"\r\n"):
        if line.lower().startswith(b"content-type:"):
            return line.split(b":", 1)[1].strip().decode("latin-1", errors="replace").split(";", 1)[0].strip().lower()
    return None


def _patch_headers(
    header_bytes: bytes,
    *,
    content_length: int | None,
    add: dict[str, str],
) -> bytes:
    """Rewrite a captured-headers blob — replace Content-Length when
    given, and append any extra headers in `add` (de-duplicating against
    existing names). Keeps the status line intact.
    """
    lines = header_bytes.split(b"\r\n")
    out: list[bytes] = []
    seen_lower: set[str] = set()
    for line in lines:
        if not line:
            continue
        if b":" in line:
            name, _, _ = line.partition(b":")
            lname = name.decode("ascii", errors="replace").lower()
            if lname == "content-length" and content_length is not None:
                continue  # rewritten below
            if lname in {k.lower() for k in add}:
                continue  # caller wants to set this
            seen_lower.add(lname)
        out.append(line)
    if content_length is not None:
        out.append(f"Content-Length: {content_length}".encode("ascii"))
    for k, v in add.items():
        out.append(f"{k}: {v}".encode("latin-1", errors="replace"))
    return b"\r\n".join(out) + b"\r\n\r\n"


# ---------------------------------------------------------------------
# API payloads
# ---------------------------------------------------------------------

def _api_report_archive_send(file: str) -> dict:
    """GET /api/report_archive_send?file= — 저장된(이미 과금된) AI 보고서를 텔레그램
    채널로 전송(재과금 없음, 사용자 2026-06-18). GET(프록시 GET-only)·인증 뒤."""
    if not file:
        return {"ok": False, "error": "file 누락"}
    try:
        from trade.report_archive import send_to_channel
        return send_to_channel(file)
    except Exception as exc:
        log.warning("report_archive_send %s: %s", file, exc)
        return {"ok": False, "error": str(exc)}


def _api_report_archive_delete(file: str) -> dict:
    """GET /api/report_archive_delete?file= — AI 보고서 아카이브 카드 삭제 (사용자
    2026-06-18 휴지통). NOAH 프록시가 GET 만 포워드하므로 GET(인증·토큰 뒤라 안전).
    report_archive.delete 가 화이트리스트 정규식으로 path traversal 차단."""
    if not file:
        return {"ok": False, "error": "file 누락"}
    try:
        from trade.report_archive import delete
        return {"ok": bool(delete(file))}
    except Exception as exc:
        log.warning("report_archive_delete %s: %s", file, exc)
        return {"ok": False, "error": str(exc)}


def _api_company_report(q: str, mode: str, leaf: str = "") -> dict:
    """GET /api/company_report?q=&mode=free|llm&leaf= — 기업 중심 보고서 HTML (사용자
    2026-06-17 '버튼으로 보고서 뽑기, 무료+유료'). mode=llm 만 비용(opt-in). leaf=히트맵
    셀 클릭 품목명(breadcrumb, 2026-06-20). graceful."""
    if not q:
        return {"ok": False, "error": "회사명 또는 6자리 코드를 입력하세요."}
    try:
        if mode in ("channel", "channel_llm"):          # 텔레그램 채널 전송
            from trade.company_report import send_to_channel
            res = send_to_channel(q, "llm" if mode == "channel_llm" else "free")
            return {"ok": res.get("ok", False), "channel": True,
                    "sent": res.get("sent", 0), "error": res.get("error")}
        from trade.company_report import build
        html = build(q, "llm" if mode == "llm" else "free", leaf=leaf or None)
        return {"ok": True, "html": html, "mode": mode}
    except Exception as exc:
        log.warning("company_report api %s/%s: %s", q, mode, exc)
        return {"ok": False, "error": str(exc)}


def _api_period_report(ym: str, mode: str) -> dict:
    """GET /api/period_report?ym=&mode=free|llm|channel — 전체 기간(월) 수출입 시장
    보고서 (사용자 2026-06-17 '전체를 다뽑을수 있게, 5월전체 식, 수출입 관계 고려').
    ym 빈값=최신월. mode=llm 만 비용(opt-in). graceful."""
    ym = (ym or "").strip() or None
    try:
        if mode in ("channel", "channel_llm"):          # 텔레그램 채널 전송
            from trade.period_report import send_to_channel
            res = send_to_channel(ym, "llm" if mode == "channel_llm" else "free")
            return {"ok": res.get("ok", False), "channel": True,
                    "sent": res.get("sent", 0), "error": res.get("error")}
        from trade.period_report import build
        html = build(ym, "llm" if mode == "llm" else "free")
        return {"ok": True, "html": html, "mode": mode}
    except Exception as exc:
        log.warning("period_report api %s/%s: %s", ym, mode, exc)
        return {"ok": False, "error": str(exc)}


def _api_alerts() -> dict:
    if not _STORE_PATH.exists():
        return {"alerts": [], "latest_ids": []}
    conn = open_db(_STORE_PATH)
    try:
        all_alerts = list_all_alerts(conn)
    finally:
        conn.close()
    seen: set[str] = set()
    latest_ids: list[int] = []
    for a in all_alerts:
        if a.get("dedup_key") not in seen:
            seen.add(a.get("dedup_key") or "")
            latest_ids.append(a["id"])
    return {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "alerts": [_payload_for_api(a, "/") for a in all_alerts],
        "latest_ids": latest_ids,
    }


def _api_health() -> dict:
    out: dict = {
        "ok": True,
        "now": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    try:
        if _STORE_PATH.exists():
            conn = open_db(_STORE_PATH)
            try:
                out["alert_count"] = stats(conn)["total"]
                row = conn.execute(
                    "SELECT MAX(posted_at) FROM alerts"
                ).fetchone()
                out["last_posted_at"] = row[0] if row and row[0] else None
            finally:
                conn.close()
        else:
            out["alert_count"] = 0
            out["last_posted_at"] = None
        if _INBOX_PATH.exists():
            out["inbox_mtime"] = time.strftime(
                "%Y-%m-%dT%H:%M:%SZ", time.gmtime(_INBOX_PATH.stat().st_mtime)
            )
        else:
            out["inbox_mtime"] = None
        # Dashboard freshness — the regen oneshot fires from a 5-minute
        # timer, so dashboard_html_mtime should be < ~300s old in healthy
        # state. Exposing both the absolute mtime AND a derived
        # 'seconds since' lets an external monitor alert on staleness
        # without re-parsing the timestamp. None when the file isn't
        # rendered yet (first boot / fresh restore).
        if _DASHBOARD_HTML.exists():
            mtime = _DASHBOARD_HTML.stat().st_mtime
            out["dashboard_html_mtime"] = time.strftime(
                "%Y-%m-%dT%H:%M:%SZ", time.gmtime(mtime)
            )
            out["dashboard_stale_seconds"] = max(0, int(time.time() - mtime))
        else:
            out["dashboard_html_mtime"] = None
            out["dashboard_stale_seconds"] = None
        usage = shutil.disk_usage("/")
        out["disk_free_gb"] = round(usage.free / (1024 ** 3), 2)
    except Exception as e:
        out["ok"] = False
        out["error"] = str(e)
    return out


def _api_stats() -> dict:
    if not _STORE_PATH.exists():
        return {"total": 0}
    conn = open_db(_STORE_PATH)
    try:
        return stats(conn)
    finally:
        conn.close()


class GatedHandler(http.server.SimpleHTTPRequestHandler):
    """SimpleHTTPRequestHandler + optional URL-token + BasicAuth.

    The token + auth checks run on every GET / HEAD; static file
    serving is otherwise unchanged from the stdlib handler, so MIME
    types, Range requests, etc. all behave as expected.
    """

    server_version = "trade-dashboard/1.0"

    def do_GET(self):  # noqa: N802 — stdlib signature
        if not self._gates_pass():
            return
        # API endpoints take precedence over static file serving.
        if self.path.startswith("/api/"):
            self._serve_api()
            return
        # Wrap the stdlib static-file serve in our gzip transform.
        self._serve_static_with_gzip(method="GET")

    def do_HEAD(self):  # noqa: N802
        if not self._gates_pass():
            return
        if self.path.startswith("/api/"):
            self._serve_api(head_only=True)
            return
        self._serve_static_with_gzip(method="HEAD")

    # --- gzip wrapper ---

    def _serve_static_with_gzip(self, method: str) -> None:
        accept = self.headers.get("Accept-Encoding", "")
        wants_gzip = "gzip" in accept
        if not wants_gzip:
            if method == "HEAD":
                super().do_HEAD()
            else:
                super().do_GET()
            return
        # Buffer the response, gzip eligible MIME types over the
        # threshold, otherwise pass-through.
        orig_wfile = self.wfile
        buf = _CapturingWFile()
        self.wfile = buf
        try:
            if method == "HEAD":
                super().do_HEAD()
            else:
                super().do_GET()
        finally:
            self.wfile = orig_wfile

        header_bytes, body_bytes = buf.split()
        mime = _pick_content_type(header_bytes)
        gzippable = (
            mime is not None
            and any(mime.startswith(p) for p in _GZIP_MIME_PREFIXES)
            and len(body_bytes) >= _GZIP_MIN_BYTES
        )
        # HTML 은 no-cache 강제 — 정적 대시보드라 브라우저가 옛 HTML/JS 를 캐싱하면
        # 배포된 수정(예: 모달 perf 인덱스)이 사용자에게 안 닿는다(사용자 2026-06-15
        # '여전히 느림' = 옛 JS 캐시 의심). NOAH 대시보드와 동일 패턴(최초 1회 강력
        # 새로고침 후 일반 새로고침으로 항상 최신).
        _nc = ({"Cache-Control": "no-cache, must-revalidate"}
               if (mime and mime.startswith("text/html")) else {})
        if gzippable and method == "GET":
            gz = gzip.compress(body_bytes)
            patched = _patch_headers(
                header_bytes,
                content_length=len(gz),
                add={"Content-Encoding": "gzip", "Vary": "Accept-Encoding", **_nc},
            )
            orig_wfile.write(patched + gz)
        elif gzippable and method == "HEAD":
            # Can't predict body size without reading the file; advertise
            # the gzip Vary but keep Content-Length the uncompressed
            # value the stdlib computed (clients use HEAD only for cache
            # validation, and Vary is the part that matters).
            patched = _patch_headers(
                header_bytes,
                content_length=None,
                add={"Vary": "Accept-Encoding", **_nc},
            )
            orig_wfile.write(patched + body_bytes)
        elif _nc:
            patched = _patch_headers(header_bytes, content_length=None, add=_nc)
            orig_wfile.write(patched + body_bytes)
        else:
            orig_wfile.write(header_bytes + body_bytes)

    # --- API endpoints ---

    def _serve_api(self, head_only: bool = False) -> None:
        path = self.path.split("?", 1)[0]
        if path == "/api/alerts.json":
            payload = _api_alerts()
        elif path == "/api/health":
            payload = _api_health()
        elif path == "/api/stats":
            payload = _api_stats()
        elif path == "/api/company_report":
            from urllib.parse import parse_qs, urlparse
            qs = parse_qs(urlparse(self.path).query)
            payload = _api_company_report((qs.get("q", [""])[0] or "").strip(),
                                          (qs.get("mode", ["free"])[0] or "free").strip(),
                                          (qs.get("leaf", [""])[0] or "").strip())
        elif path == "/api/period_report":
            from urllib.parse import parse_qs, urlparse
            qs = parse_qs(urlparse(self.path).query)
            payload = _api_period_report((qs.get("ym", [""])[0] or "").strip(),
                                         (qs.get("mode", ["free"])[0] or "free").strip())
        elif path == "/api/report_archive_delete":
            from urllib.parse import parse_qs, urlparse
            qs = parse_qs(urlparse(self.path).query)
            payload = _api_report_archive_delete((qs.get("file", [""])[0] or "").strip())
        elif path == "/api/report_archive_send":
            from urllib.parse import parse_qs, urlparse
            qs = parse_qs(urlparse(self.path).query)
            payload = _api_report_archive_send((qs.get("file", [""])[0] or "").strip())
        else:
            self.send_error(404)
            return
        body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        accept = self.headers.get("Accept-Encoding", "")
        if "gzip" in accept and len(body) >= _GZIP_MIN_BYTES:
            body = gzip.compress(body)
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Encoding", "gzip")
            self.send_header("Vary", "Accept-Encoding")
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
        else:
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
        if not head_only:
            self.wfile.write(body)

    def _gates_pass(self) -> bool:
        # 공개 스냅샷 경로(/share/<token>/YYYY-MM.html)는 BasicAuth·운영 토큰
        # 면제. 단 그 prefix 안에서도 'YYYY-MM.html' 월별 스냅샷만 서빙 — 그 외
        # 경로(예: /share/<token>/index.html)는 404로 차단해 토큰 노출만으로
        # 라이브 대시보드가 새지 않게 한다.
        path = self.path.split("?", 1)[0]
        if path.startswith(_PUBLIC_PREFIX):
            rest = path[len(_PUBLIC_PREFIX):].lstrip("/")
            if _SHARE_FILE_RE.match(rest):                 # 'YYYY-MM.html'만
                self.path = f"/dashboard/share/{rest}"     # 월별 스냅샷으로 rewrite
                return True
            self.send_error(404)
            return False
        if not self._check_auth():
            return False
        if not self._check_token():
            return False
        return True

    # --- BasicAuth ---

    def _check_auth(self) -> bool:
        if not (_AUTH_USER and _AUTH_PASSWORD):
            return True
        header = self.headers.get("Authorization", "")
        if not header.startswith("Basic "):
            self._challenge()
            return False
        try:
            decoded = base64.b64decode(header[6:]).decode("utf-8")
            user, sep, password = decoded.partition(":")
        except Exception:
            self._challenge()
            return False
        if not sep or user != _AUTH_USER or password != _AUTH_PASSWORD:
            self._challenge()
            return False
        return True

    def _challenge(self) -> None:
        self.send_response(401)
        self.send_header("WWW-Authenticate", 'Basic realm="trade"')
        self.send_header("Content-Length", "0")
        self.end_headers()

    # --- URL token ---

    def _check_token(self) -> bool:
        if not _TOKEN:
            return True
        path = self.path.lstrip("/")
        first, sep, rest = path.partition("/")
        if first != _TOKEN:
            self.send_error(404)
            return False
        # Rewrite so SimpleHTTPRequestHandler serves files relative to
        # data_dir as if the token weren't there.
        self.path = "/" + rest if rest else "/"
        return True

    def log_message(self, fmt: str, *args) -> None:
        # Quieter access log; keep stderr for warnings only.
        try:
            status = args[1] if len(args) > 1 else ""
            if isinstance(status, str) and status.startswith(("4", "5")):
                log.warning("%s %s", self.address_string(), fmt % args)
        except Exception:
            pass


class _ThreadingHTTPServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    """ThreadingHTTPServer wasn't always exported on older Pythons;
    build it here so multiple browser tabs / image requests don't
    serialize behind each other.
    """

    daemon_threads = True
    allow_reuse_address = True


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Static file server for the trade dashboard."
    )
    ap.add_argument("--port", type=int, default=8765)
    ap.add_argument("--bind", default="0.0.0.0")
    ap.add_argument(
        "--data-dir",
        type=Path,
        default=Path(os.environ.get("TRADE_DATA_DIR") or Path.home() / ".trade"),
    )
    args = ap.parse_args()

    if not args.data_dir.exists():
        print(f"error: data dir not found: {args.data_dir}", file=sys.stderr)
        return 1

    logging.basicConfig(
        format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
        level=logging.INFO,
    )
    handler = partial(GatedHandler, directory=str(args.data_dir))
    server = _ThreadingHTTPServer((args.bind, args.port), handler)
    log.info(
        "serving %s on http://%s:%d (token=%s auth=%s)",
        args.data_dir,
        args.bind,
        args.port,
        "ON" if _TOKEN else "off",
        "ON" if (_AUTH_USER and _AUTH_PASSWORD) else "off",
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
