"""Static-file HTTP server for the trade dashboard.

Serves ~/.trade/ as the document root, so /dashboard/index.html and
/media/<date>/<uid>.jpg both resolve naturally from the index.html
generated by trade.dashboard.

Two optional gates:
  - URL token: TRADE_DASHBOARD_TOKEN — requests must include /<token>/...
    as the path prefix; the token is stripped before file resolution.
  - HTTP Basic Auth: TRADE_DASHBOARD_USER + TRADE_DASHBOARD_PASSWORD.

Both empty = server is open. Pick at least Basic Auth if exposing the
port on the public internet.

Usage:
    python -m trade.dashboard_server [--port 8082] [--bind 0.0.0.0]
"""

import argparse
import base64
import http.server
import logging
import os
import socketserver
import sys
from functools import partial
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

_TOKEN = (os.environ.get("TRADE_DASHBOARD_TOKEN") or "").strip()
_AUTH_USER = (os.environ.get("TRADE_DASHBOARD_USER") or "").strip()
_AUTH_PASSWORD = (os.environ.get("TRADE_DASHBOARD_PASSWORD") or "").strip()

log = logging.getLogger("trade-dashboard")


class GatedHandler(http.server.SimpleHTTPRequestHandler):
    """SimpleHTTPRequestHandler + optional URL-token + BasicAuth.

    The token + auth checks run on every GET / HEAD; static file
    serving is otherwise unchanged from the stdlib handler, so MIME
    types, Range requests, etc. all behave as expected.
    """

    server_version = "trade-dashboard/1.0"

    def do_GET(self):  # noqa: N802 — stdlib signature
        if not self._gates_pass():
            return
        super().do_GET()

    def do_HEAD(self):  # noqa: N802
        if not self._gates_pass():
            return
        super().do_HEAD()

    def _gates_pass(self) -> bool:
        if not self._check_auth():
            return False
        if not self._check_token():
            return False
        return True

    # --- BasicAuth ---

    def _check_auth(self) -> bool:
        if not (_AUTH_USER and _AUTH_PASSWORD):
            return True
        header = self.headers.get("Authorization", "")
        if not header.startswith("Basic "):
            self._challenge()
            return False
        try:
            decoded = base64.b64decode(header[6:]).decode("utf-8")
            user, sep, password = decoded.partition(":")
        except Exception:
            self._challenge()
            return False
        if not sep or user != _AUTH_USER or password != _AUTH_PASSWORD:
            self._challenge()
            return False
        return True

    def _challenge(self) -> None:
        self.send_response(401)
        self.send_header("WWW-Authenticate", 'Basic realm="trade"')
        self.send_header("Content-Length", "0")
        self.end_headers()

    # --- URL token ---

    def _check_token(self) -> bool:
        if not _TOKEN:
            return True
        path = self.path.lstrip("/")
        first, sep, rest = path.partition("/")
        if first != _TOKEN:
            self.send_error(404)
            return False
        # Rewrite so SimpleHTTPRequestHandler serves files relative to
        # data_dir as if the token weren't there.
        self.path = "/" + rest if rest else "/"
        return True

    def log_message(self, fmt: str, *args) -> None:
        # Quieter access log; keep stderr for warnings only.
        try:
            status = args[1] if len(args) > 1 else ""
            if isinstance(status, str) and status.startswith(("4", "5")):
                log.warning("%s %s", self.address_string(), fmt % args)
        except Exception:
            pass


class _ThreadingHTTPServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    """ThreadingHTTPServer wasn't always exported on older Pythons;
    build it here so multiple browser tabs / image requests don't
    serialize behind each other.
    """

    daemon_threads = True
    allow_reuse_address = True


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Static file server for the trade dashboard."
    )
    ap.add_argument("--port", type=int, default=8082)
    ap.add_argument("--bind", default="0.0.0.0")
    ap.add_argument(
        "--data-dir",
        type=Path,
        default=Path(os.environ.get("TRADE_DATA_DIR") or Path.home() / ".trade"),
    )
    args = ap.parse_args()

    if not args.data_dir.exists():
        print(f"error: data dir not found: {args.data_dir}", file=sys.stderr)
        return 1

    logging.basicConfig(
        format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
        level=logging.INFO,
    )
    handler = partial(GatedHandler, directory=str(args.data_dir))
    server = _ThreadingHTTPServer((args.bind, args.port), handler)
    log.info(
        "serving %s on http://%s:%d (token=%s auth=%s)",
        args.data_dir,
        args.bind,
        args.port,
        "ON" if _TOKEN else "off",
        "ON" if (_AUTH_USER and _AUTH_PASSWORD) else "off",
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
