"""Screener 도메인 표시 라벨 — **영문 (한글)** 통일 (사용자 2026-08-18).

목록이 네 가지 형식으로 갈려 있었다(339개 중): `Aerospace & Defense (항공우주
및 방위)` 처럼 영문+한글인 것 62개, `Air Freight & Logistics(Transportation &
Logistics)` 처럼 괄호에 **부모 L3 영문**이 든 것 251개, 한글만 10개, 영문만 5개.
사용자 요청은 전부 `영문 (한글)` 로 통일.

⚠️ **THEME["domain"] 은 건드리지 않는다.** 그 문자열은 LLM 프롬프트 컨텍스트와
아카이브에 이미 들어가 있어 바꾸면 과거 산출물과 어긋난다. 대신 여기 **표시
라벨 단일 레지스트리**를 두고 화면·텔레그램이 같은 함수를 쓴다(§Help 단일
레지스트리 규칙). 새 도메인 모듈을 넣으면 회귀 테스트가 이 표의 누락을 잡는다.

한글은 라벨이지 수치가 아니다 — 그래도 업계 통용어를 썼고, 원문 영문을 항상
왼쪽에 남겨 오역이 있어도 원본을 잃지 않게 했다.
"""
from __future__ import annotations

import re

# 슬러그 → 한글 라벨. 영문은 THEME["domain"] 에서 뽑는다(괄호 안 부모명 제거).
KO: dict[str, str] = {
    "aerospace_defense_commercial_aviation_oem": "상업용 항공기 OEM",
    "aerospace_defense_drones_counter_uas": "드론 및 대드론",
    "aerospace_defense_military_prime": "군용 주계약업체",
    "aerospace_defense_naval_shipbuilding": "함정 조선",
    "aerospace_defense_space_launch": "우주 발사 및 위성",
    "aerospace_defense_sub_tier": "항공 부품 협력사",
    "airlines_asia_low_cost": "아시아 저비용 항공",
    "airlines_asia_premium": "아시아 프리미엄 항공",
    "airlines_eu_flag_carriers": "유럽 국적 항공사",
    "airlines_eu_low_cost": "유럽 저비용 항공",
    "airlines_us_low_cost": "미국 저비용 항공",
    "airlines_us_network_carriers": "미국 네트워크 항공사",
    "apparel_luxury_eu_ch": "유럽·스위스 시계 및 보석",
    "apparel_luxury_eu_hard_luxury": "유럽 하드 럭셔리",
    "apparel_luxury_fast_fashion_asia": "패스트패션 및 아시아",
    "apparel_luxury_us": "미국 애슬레저",
    "apparel_luxury_us_apparel": "미국 의류 및 액세서리",
    "automotive_auto_parts_adas": "자동차 부품 및 ADAS",
    "automotive_auto_retail": "자동차 유통",
    "automotive_ev_pure_play": "순수 전기차",
    "automotive_ice_hybrid_oem": "내연기관·하이브리드 완성차",
    "automotive_luxury_oem": "럭셔리 완성차",
    "automotive_tire": "타이어",
    "banks_china_joint_stock_insuranc": "중국 국유·주식제 은행 및 보험",
    "banks_global_gsib": "글로벌 시스템적 중요 은행",
    "banks_japan_mega_banks": "일본 메가뱅크",
    "banks_korea": "한국 금융지주",
    "banks_us_big_4_diversified": "미국 4대 종합은행",
    "banks_us_regional": "미국 지역은행",
    "bdc": "사업개발회사",
    "bdc_pe_sponsor_affiliated": "PE 스폰서 계열",
    "bdc_tier_1_externally_managed": "1군 — 외부위탁 대형 BDC",
    "bdc_tier_2_internally_managed": "2군 — 내부운용 우량",
    "bdc_tier_3_specialty_niche": "3군 — 특화 니치",
    "bdc_venture_debt_focused": "벤처 대출 특화",
    "beverages_beer": "맥주",
    "beverages_energy_drinks_functional": "에너지드링크 및 기능성 음료",
    "beverages_japan_korea": "일본·한국 주류",
    "beverages_non_alcoholic_soft_drinks": "무알코올·탄산음료",
    "beverages_spirits_wine": "증류주 및 와인",
    "beverages_sub": "중국 백주",
    "bottleneck": "AI 데이터센터 증설",
    "building_products_building_products_distribu": "건축자재 유통",
    "building_products_elevators_escalators": "엘리베이터 및 에스컬레이터",
    "building_products_engineering_construction": "엔지니어링 및 건설",
    "building_products_hvac": "냉난방공조",
    "building_products_insulation_roofing": "단열재 및 지붕재",
    "building_products_water_heating": "급탕 설비",
    "capital_markets_asset_management_alternati": "자산운용 — 대체투자",
    "capital_markets_asset_management_tradition": "자산운용 — 전통자산",
    "capital_markets_financial_data_ratings": "금융 데이터 및 신용평가",
    "capital_markets_financial_exchanges": "거래소",
    "capital_markets_investment_banking_brokera": "투자은행 및 증권중개",
    "carbon_capture": "탄소 포집·활용·저장",
    "chemicals_agricultural_chemicals": "농약 및 비료",
    "chemicals_diversified_specialty": "종합 및 정밀화학",
    "chemicals_industrial_gases": "산업용 가스",
    "chemicals_petrochemicals": "석유화학",
    "chemicals_specialty_for_ev_battery_s": "전기차 배터리·반도체용 정밀화학",
    "commercial_services_facility_services": "시설관리 서비스",
    "commercial_services_payroll_hcm": "급여 및 인사관리",
    "commercial_services_research_data_analytics": "리서치 및 데이터 분석",
    "commercial_services_security": "보안 서비스",
    "commercial_services_staffing_recruitment": "인력파견 및 채용",
    "communication": "커뮤니케이션 서비스",
    "construction_materials_asia_cement_korea_japan": "아시아·한국·일본 시멘트",
    "construction_materials_china_cement": "중국 시멘트",
    "construction_materials_concrete_ready_mix": "콘크리트 및 레미콘",
    "construction_materials_global_cement": "글로벌 시멘트",
    "construction_materials_us_aggregates_cement": "미국 골재 및 시멘트",
    "consumer_finance_auto_student_lending": "자동차·학자금 대출",
    "consumer_finance_card_networks_duopoly": "카드 네트워크 복점",
    "consumer_finance_mortgage_finance": "주택담보대출 금융",
    "consumer_finance_premium_card_travel": "프리미엄 카드 및 여행",
    "consumer_finance_subprime_private_label": "서브프라임 및 자체 카드",
    "defense": "방위·항공우주 및 우주",
    "digital_assets_bitcoin_mining_hashrate_pu": "비트코인 채굴 및 해시레이트",
    "digital_assets_bitcoin_treasury_strategy": "비트코인 보유 전략",
    "digital_assets_blockchain_infrastructure": "블록체인 인프라",
    "digital_assets_crypto_exchanges": "가상자산 거래소",
    "digital_assets_spot_bitcoin_ethereum_etf": "현물 비트코인·이더리움 ETF 운용사",
    "digital_assets_stablecoin_ecosystem": "스테이블코인 생태계",
    "education_services_children_s_learning_toys": "아동 학습 및 완구",
    "education_services_higher_ed_online_universit": "고등교육 및 온라인 대학",
    "education_services_k_12_online_tutoring": "K-12 및 온라인 과외",
    "education_services_korean_hagwon_asia": "한국 학원 및 아시아 사교육",
    "education_services_test_prep_standardized_tes": "입시 준비 및 표준화 시험",
    "electric_utility_california": "캘리포니아 전력",
    "electric_utility_mega_cap_regulated": "초대형 규제 전력",
    "electric_utility_mid_cap_regulated": "중형 규제 전력",
    "electric_utility_multi_utility_combined": "복합 유틸리티",
    "electric_utility_texas_ercot": "텍사스 및 ERCOT",
    "electrical_equipment_backup_generator_ats": "비상 발전기 및 자동절체스위치",
    "electrical_equipment_gis": "가스절연 개폐장치",
    "electrical_equipment_industrial_automation": "산업 자동화",
    "electrical_equipment_power_cable": "전력 케이블",
    "electrical_equipment_transformer": "변압기",
    "electrical_equipment_ups_data_center_power_mgmt": "UPS 및 데이터센터 전력관리",
    "energy_services_drilling_contractors_offsh": "시추 계약 — 해양",
    "energy_services_drilling_contractors_onsho": "시추 계약 — 육상",
    "energy_services_frac_pressure_pumping": "수압파쇄 및 압력펌핑",
    "energy_services_integrated_oilfield_servic": "종합 유전 서비스",
    "energy_services_ofs_equipment_tools": "유전 장비 및 툴",
    "energy_services_subsea_epc": "해저 및 해상 EPC",
    "entertainment_cinema_movie_theater": "영화관",
    "entertainment_japanese_animation_studios": "일본 애니메이션 스튜디오",
    "entertainment_korean_entertainment_big_4": "한국 엔터 4대사",
    "entertainment_live_events_sports": "라이브 공연 및 스포츠",
    "entertainment_music_streaming_labels": "음악 스트리밍 및 레이블",
    "entertainment_streaming_studio": "스트리밍 및 스튜디오",
    "ev": "전기차 및 배터리",
    "food_products_agricultural_commodities_t": "농산물 및 곡물 트레이딩",
    "food_products_dairy_yogurt": "유제품 및 요거트",
    "food_products_frozen_specialty": "냉동 및 특수식품",
    "food_products_meat_protein": "육류 및 단백질",
    "food_products_packaged_foods": "가공식품",
    "food_products_snacks_confectionery": "스낵 및 제과",
    "food_retailing_convenience_stores": "편의점",
    "food_retailing_dollar_stores": "달러스토어",
    "food_retailing_eu_asia_grocery": "유럽·아시아 식품유통",
    "food_retailing_mass_merchant_warehouse_cl": "대형마트 및 창고형 클럽",
    "food_retailing_traditional_grocery": "전통 슈퍼마켓",
    "forest_paper_pulp_paper_brands": "펄프 및 제지 브랜드",
    "forest_paper_specialty_paper_tissue": "특수지 및 위생용지",
    "forest_paper_timber_lumber": "임업 및 목재",
    "forest_paper_wood_products_building": "목재 제품 및 건축재",
    "gaming_aaa_publishers": "AAA 게임 퍼블리셔",
    "gaming_console_mfg_platform": "콘솔 제조 및 플랫폼",
    "gaming_japanese_mobile_anime_swit": "일본 모바일·애니 및 스위치",
    "gaming_korean_mobile_pc": "한국 모바일·PC 게임",
    "gaming_online_mobile": "온라인 및 모바일 게임",
    "gaming_web3_blockchain_gaming": "웹3 및 블록체인 게임",
    "gas_water_asia_gas_water": "아시아 가스 및 수도",
    "gas_water_eu_water_gas": "유럽 수도 및 가스",
    "gas_water_regulated_gas_distribution": "규제 가스 공급",
    "gas_water_water_equipment_tech": "수처리 장비 및 기술",
    "gas_water_water_wastewater_us": "미국 상하수도",
    "hardware_storage_communications_equipment_a": "통신장비 및 AI 패브릭 스위치",
    "hardware_storage_consumer_electronics": "가전",
    "hardware_storage_networking_connectivity": "네트워킹 및 커넥티비티",
    "hardware_storage_storage_devices_memory_for": "스토리지 및 메모리 모듈",
    "hardware_storage_taiwan_odm_ems": "대만 ODM·EMS",
    "hardware_storage_tech_hardware": "IT 하드웨어",
    "healthcare_providers_animal_health_diagnostics": "동물 헬스케어 및 진단",
    "healthcare_providers_diagnostics_research_cro": "진단·연구 및 CRO",
    "healthcare_providers_digital_health_telehealth": "디지털 헬스 및 원격진료",
    "healthcare_providers_hospitals_care_facilities": "병원 및 요양시설",
    "healthcare_providers_managed_health_care": "관리형 의료보험",
    "healthcare_providers_medical_distribution": "의약품 유통",
    "homebuilding_building_products": "건축 자재",
    "homebuilding_home_furnishings": "가구 및 홈퍼니싱",
    "homebuilding_manufactured_homes_modular": "조립주택 및 모듈러",
    "homebuilding_multi_family_build_to_rent": "다세대 및 임대전용 주택",
    "homebuilding_single_family_homebuilders": "단독주택 건설",
    "hospitality_cruise_lines": "크루즈",
    "hospitality_fast_casual_qsr_restaurant": "패스트캐주얼 및 QSR",
    "hospitality_full_service_specialty_res": "풀서비스 및 전문 레스토랑",
    "hospitality_gambling_casino_operators": "카지노 및 게이밍",
    "hospitality_hotels_resorts": "호텔 및 리조트",
    "hospitality_travel_ota": "여행 및 온라인 여행사",
    "household_personal_household_cleaning_paper": "가정용 세제 및 종이제품",
    "household_personal_japan_cosmetics_skincare": "일본 화장품 및 스킨케어",
    "household_personal_korea_k_beauty": "한국 K-뷰티",
    "household_personal_mass_cosmetics_personal_ca": "매스 화장품 및 퍼스널케어",
    "household_personal_oral_care_hygiene": "구강 관리 및 위생",
    "household_personal_premium_cosmetics": "프리미엄 화장품",
    "insurance_insurance_brokers": "보험 중개",
    "insurance_life_health": "생명 및 건강보험",
    "insurance_p_c_auto_home": "손해보험 — 자동차·주택",
    "insurance_p_c_commercial_specialty": "손해보험 — 기업성·특종",
    "insurance_reinsurance": "재보험",
    "interactive_media_china_internet_mega_cap": "중국 인터넷 대형주",
    "interactive_media_dating_matching": "데이팅 및 매칭",
    "interactive_media_direct_to_consumer_marketp": "D2C 및 마켓플레이스",
    "interactive_media_korea_japan_internet": "한국·일본 인터넷",
    "interactive_media_search_advertising": "검색 및 광고",
    "interactive_media_social_media": "소셜미디어",
    "ipp_renewable_ess_integrator_storage": "ESS 통합 및 저장장치",
    "ipp_renewable_eu_uk_offshore_wind_develo": "유럽·영국 해상풍력 개발",
    "ipp_renewable_geothermal_hydrogen": "지열 및 수소",
    "ipp_renewable_us_ipp": "미국 민자발전",
    "ipp_renewable_us_solar": "미국 태양광",
    "ipp_renewable_wind_turbine_oem": "풍력터빈 제조",
    "it_fintech_buy_now_pay_later_online_l": "후불결제 및 온라인 대출",
    "it_fintech_card_networks_payment_rail": "카드 네트워크 및 결제망",
    "it_fintech_india_it_outsourcing": "인도 IT 아웃소싱",
    "it_fintech_it_services_consulting": "IT 서비스 및 컨설팅",
    "it_fintech_payment_processing_fintech": "결제 처리 및 핀테크",
    "it_fintech_specialty_financial_softwa": "금융 특화 소프트웨어",
    "machinery_bearings_power_transmissio": "베어링 및 동력전달",
    "machinery_diesel_engines_powertrain": "디젤엔진 및 파워트레인",
    "machinery_factory_automation": "공장 자동화",
    "machinery_farm_machinery": "농기계",
    "machinery_general_industrial": "일반 산업기계",
    "machinery_heavy_construction": "중장비 및 건설기계",
    "medical_equipment_cardiovascular": "심혈관 의료기기",
    "medical_equipment_dental_vision": "치과 및 안과",
    "medical_equipment_diabetes_care_cgm": "당뇨 관리 및 연속혈당측정",
    "medical_equipment_diagnostic_imaging_lab_too": "영상진단 및 실험장비",
    "medical_equipment_orthopedic_implants": "정형외과 임플란트",
    "medical_equipment_surgical_devices_robotics": "수술기기 및 로보틱스",
    "metals_mining_aluminum": "알루미늄",
    "metals_mining_copper_diversified": "구리 및 종합 광업",
    "metals_mining_lithium": "리튬",
    "metals_mining_precious_metals": "귀금속",
    "metals_mining_rare_earth": "희토류",
    "metals_mining_steel": "철강",
    "oil_gas_coal_thermal_metallurgical": "연료탄 및 원료탄",
    "oil_gas_e_p_us_shale_focused": "미국 셰일 E&P",
    "oil_gas_integrated_majors": "종합 석유 메이저",
    "oil_gas_lng_producers_infra": "LNG 생산 및 인프라",
    "oil_gas_midstream": "미드스트림",
    "oil_gas_refining_marketing": "정유 및 판매",
    "oil_gas_uranium_mining_enrichment": "우라늄 채굴 및 농축",
    "packaging_glass_specialty": "유리 및 특수 포장",
    "packaging_metal_containers_beverage": "금속 용기 및 음료캔",
    "packaging_paper_corrugated_box": "제지 및 골판지 상자",
    "packaging_plastic_flexible": "플라스틱 및 연포장",
    "packaging_sustainable_bio_based_pack": "친환경·바이오 기반 포장",
    "pharma": "바이오 및 제약",
    "pharma_biotech": "제약 및 바이오테크",
    "pharma_biotech_adc": "항체약물접합체",
    "pharma_biotech_ai_drug_discovery": "AI 신약 발굴",
    "pharma_biotech_biotechnology": "바이오테크",
    "pharma_biotech_cell_gene_therapy": "세포·유전자 치료",
    "pharma_biotech_major_pharmaceuticals": "대형 제약",
    "pharma_biotech_specialty_generic_pharma": "특수·제네릭 의약품",
    "real_estate_services_commercial_real_estate_bro": "상업용 부동산 중개",
    "real_estate_services_property_listings_data": "부동산 매물 및 데이터",
    "real_estate_services_property_management_tech": "부동산 관리 및 프롭테크",
    "real_estate_services_residential_brokerage_mort": "주거용 중개 및 모기지",
    "reits": "리츠",
    "reits_data_center_reits": "데이터센터 리츠",
    "reits_healthcare_reits": "헬스케어 리츠",
    "reits_industrial_reits": "물류·산업 리츠",
    "reits_mortgage_reits": "모기지 리츠",
    "reits_office_reits": "오피스 리츠",
    "reits_residential_reits": "주거 리츠",
    "reits_retail_reits": "리테일 리츠",
    "reits_specialty_reits": "특수 리츠",
    "retail_beauty_personal_care": "뷰티 및 퍼스널케어 유통",
    "retail_broadline_retail_discounte": "종합 소매 및 할인점",
    "retail_e_commerce_direct_marketin": "이커머스 및 다이렉트 마케팅",
    "retail_home_improvement": "홈임프루브먼트",
    "retail_specialty_retail": "전문 소매",
    "robot": "로보틱스 및 휴머노이드 증설",
    "software_application_crm_erp": "애플리케이션 — CRM/ERP",
    "software_application_productivity_a": "애플리케이션 — 생산성 및 AI 에이전트",
    "software_cloud_database": "클라우드 및 데이터베이스",
    "software_cybersecurity": "사이버보안",
    "software_enterprise_vertical_saas": "엔터프라이즈 버티컬 SaaS",
    "software_observability_devops": "옵저버빌리티 및 데브옵스",
    "solar": "태양광·풍력·ESS 및 전력망",
    "telecom": "통신 서비스",
    "telecom_asia_4_mega_tier": "아시아 4대 통신",
    "telecom_communication_infrastructu": "통신 인프라 리츠",
    "telecom_eu_integrated": "유럽 종합 통신",
    "telecom_korea_specialty_telecom": "한국 및 특화 통신",
    "telecom_us_cable_broadband": "미국 케이블 및 브로드밴드",
    "telecom_us_integrated_wireless": "미국 종합 무선통신",
    "tobacco": "담배",
    "tobacco_eu_uk": "유럽·영국 담배",
    "tobacco_international": "인터내셔널 담배",
    "tobacco_japan": "일본 담배",
    "tobacco_korea_asia": "한국 및 아시아 담배",
    "tobacco_us_domestic": "미국 내수 담배",
    "tobacco_vape_nicotine_pouch": "차세대 전자담배 및 니코틴 파우치",
    "transport_logistics_air_freight_logistics": "항공화물 및 물류",
    "transport_logistics_marine_shipping": "해운",
    "transport_logistics_railroads": "철도",
    "transport_logistics_ride_share_last_mile": "차량공유 및 라스트마일",
    "transport_logistics_trucking_ground": "트럭 및 육상운송",
    "waste_management_environmental_consulting_r": "환경 컨설팅 및 정화",
    "waste_management_hazardous_waste_industrial": "유해폐기물 및 산업세정",
    "waste_management_recycling_recovery": "재활용 및 자원회수",
    "waste_management_solid_waste_collection": "생활폐기물 수거",
    "waste_management_water_wastewater_treatment": "상하수 처리",
}

# 도메인 문자열이 **한글로 시작**해 영문을 뽑을 수 없는 항목만 여기서 보충.
EN: dict[str, str] = {
    "aerospace_defense_commercial_aviation_oem": "Commercial Aviation OEM",
    "aerospace_defense_drones_counter_uas": "Drones & Counter-UAS",
    "aerospace_defense_military_prime": "Military Prime",
    "aerospace_defense_naval_shipbuilding": "Naval Shipbuilding",
    "aerospace_defense_space_launch": "Space Launch & Satellites",
    "aerospace_defense_sub_tier": "Sub-tier Suppliers",
    "apparel_luxury_eu_ch": "EU/CH Watches & Jewelry",
    "apparel_luxury_us": "US Athletic Apparel",
    "apparel_luxury_us_apparel": "US Apparel & Accessories",
    "banks_korea": "Korea Financial Holdings",
    "beverages_japan_korea": "Japan & Korea Brewers",
    "beverages_sub": "China Baijiu",
    "chemicals_agricultural_chemicals": "Agricultural Chemicals & Fertilizers",
    "communication": "Communication Services",
    "education_services_korean_hagwon_asia": "Korean Hagwon & Asia Private Education",
    "energy_services_subsea_epc": "Subsea & Offshore EPC",
    "pharma_biotech": "Pharmaceuticals & Biotechnology",
    "reits": "REITs",
    "telecom": "Telecommunication Services",
    "tobacco": "Tobacco",
    "tobacco_vape_nicotine_pouch": "Next-gen Vape & Nicotine Pouch",
}

_HANGUL = re.compile(r"[가-힣]")
_TRAIL_PAREN = re.compile(r"\s*\(([^()]*)\)\s*$")


def display_domain(slug: str, raw: str) -> str:
    """`영문 (한글)`. 규약을 못 채우면 원문 그대로 — 지어내지 않는다."""
    raw = (raw or "").strip()
    if not raw:
        return ""
    en = EN.get(slug)
    if not en:
        # 끝의 괄호는 부모 L3 영문명이라 라벨에선 뺀다(계층은 화면이 이미 보여줌).
        # 단 괄호 안에 한글이 있으면 그건 이미 우리가 원하는 형식이다.
        m = _TRAIL_PAREN.search(raw)
        if m and _HANGUL.search(m.group(1)):
            return raw
        en = _TRAIL_PAREN.sub("", raw).strip() if m else raw
    ko = KO.get(slug)
    return f"{en} ({ko})" if ko else en


def missing_labels(domains: dict) -> list[str]:
    """`display_domain` 이 `영문 (한글)` 를 못 만드는 슬러그 — 회귀 테스트용.

    새 도메인 모듈을 drop 하면 여기 걸린다(#24 '목록형 가드' 대신 전수 대조)."""
    bad = []
    for slug, raw in domains.items():
        out = display_domain(slug, raw)
        m = _TRAIL_PAREN.search(out)
        if not (m and _HANGUL.search(m.group(1))
                and not _HANGUL.search(out[:m.start()])):
            bad.append(slug)
    return bad

# 계층 헤딩도 같은 규약(`영문 (한글)`). 대시보드·텔레그램이 **같은 표**를 쓴다 —
# 두 곳에 문자열을 두었더니 대시보드만 "🎯 L4 세부 업종" 으로 바뀌고 텔레그램은
# "🎯 L4 Sub-industry" 로 남아 회귀 테스트가 계속 빨간 채였다(2026-08-18 발견).
LAYER_LABELS: dict[str, str] = {
    "L1_TREND": "📈 L1 Trend (트렌드)",
    "L2_SECTOR": "🏢 L2 Sector (섹터)",
    "L3_INDUSTRY": "🔬 L3 Industry (산업)",
    "L4_SUBINDUSTRY": "🎯 L4 Sub-industry (세부 업종)",
    "AD_HOC": "🆕 Ad-hoc Promoted (자유어 승격)",
}


def layer_label(layer: str) -> str:
    return LAYER_LABELS.get(layer, layer)
