"""Read the Standard View daily macro brief and surface it to NOAH
analysts as supplementary macro context.

Phase B-1 (Step 2A, 2026-05-19) — first integration step between NOAH
stock-bot and the higgack/standardview deploy (same host: telegram-bot
VM, /home/higgack/standardview). Standard View runs a daily systemd
timer at 08:00 KST that produces:

    ~/standardview/reports/generated/{YYYY-MM-DD}.md   (telegram body)
    ~/standardview/reports/generated/{YYYY-MM-DD}.html (full dashboard)

This module reads the .md, strips header meta, and renders it as an
analyst-prompt directive that ``build_instrument_context`` appends to
the macro block. Universal-by-default — every market (US/KR/JP/TW/CN)
receives the brief because it covers global macro variables (Fed /
유가 / 달러 / 지정학) that influence every market's 5-day price action,
not just KR.

Failure modes (silent degradation — never raises):
 • file missing (timer not fired yet on a fresh deploy) → today + yesterday
   fallback; if both absent, return ''
 • read error / permission → log warning + return ''
 • environment without /home/higgack/standardview/ (e.g. local dev VM) →
   ''. NOAH continues without the StandardView block.

Source attribution: StanLee5767/standardview (license received, see
bot/dart_client.py for the same attribution context). The .md is
generated by a Gemini API call (model: gemini-2.5-flash) on the
StandardView FastAPI backend; NOAH does not call Gemini twice for it.
"""

from __future__ import annotations

import logging
import os
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

log = logging.getLogger("bot.standardview")

# Standard View output directory on the telegram-bot host. Same VM as
# NOAH — direct file read, no HTTP. Configurable via env var to ease
# local-dev testing or future relocation.
STANDARDVIEW_REPORTS = Path(
    os.environ.get(
        "STANDARDVIEW_REPORTS_DIR",
        "/home/higgack/standardview/reports/generated",
    )
)

# Per-day cache (in-process). Avoids re-reading the same MD on every
# analyst call within one bot session. The .md is written exactly once
# per day by the systemd timer, so a stale cache after midnight is
# acceptable until the bot restarts (which happens via auto-update or
# manual restart well before the next 08:00 fire).
_CACHE: dict[str, Optional[str]] = {}

# Prompt-budget cap. The .md is typically 3-4KB but Gemini's
# 매크로 동향 / Market Moving Issues / 4 comment cards 합쳐 더 길어질
# 수도 있어 안전하게 3000 자에서 truncate. Analyst prompt 가 이미
# 매크로 block + instrument metadata + corp actions 등으로 큼.
_MAX_BRIEF_CHARS = 3000


def get_standardview_brief(target_date: Optional[str] = None) -> Optional[str]:
    """Return Standard View daily brief MD text, or None when absent.

    Lookback order: today → yesterday. The 08:00 KST timer may not have
    fired yet (e.g. analyst runs at 07:30) — fall back to yesterday's
    brief in that case rather than skipping entirely.
    """
    if target_date is None:
        target_date = date.today().isoformat()

    if target_date in _CACHE:
        return _CACHE[target_date]

    try:
        today_date = date.fromisoformat(target_date)
    except ValueError:
        log.warning("standardview: invalid target_date %s", target_date)
        return None
    candidates = [
        target_date,
        (today_date - timedelta(days=1)).isoformat(),
    ]

    for d in candidates:
        path = STANDARDVIEW_REPORTS / f"{d}.md"
        if not path.exists():
            continue
        try:
            text = path.read_text(encoding="utf-8")
            _CACHE[target_date] = text
            log.info(
                "standardview brief loaded: %s (%d chars)",
                d, len(text),
            )
            return text
        except Exception as exc:
            log.warning(
                "standardview brief read failed for %s: %s", d, exc,
            )

    log.info(
        "standardview brief not found (tried %s)",
        ", ".join(candidates),
    )
    _CACHE[target_date] = None
    return None


def _strip_header_meta(brief_md: str) -> str:
    """Drop the leading title + date + '---' separator. Standard View MD
    header looks like:

        # Standard View — Daily Brief
        **2026-05-19** | 생성: 2026-05-19 21:11 KST

        ---

    Everything from the first '---' onward is the actual content."""
    lines = brief_md.splitlines()
    body_start = 0
    for i, ln in enumerate(lines):
        if ln.strip() == "---":
            body_start = i + 1
            break
    return "\n".join(lines[body_start:]).strip()


def format_for_macro_directive(brief_md: Optional[str]) -> str:
    """Render the Standard View brief as a directive block for the
    analyst prompt. Empty string when brief is None — caller appends
    nothing in that case."""
    if not brief_md:
        return ""
    body = _strip_header_meta(brief_md)
    if not body:
        return ""
    if len(body) > _MAX_BRIEF_CHARS:
        body = body[:_MAX_BRIEF_CHARS] + "\n…[truncated]"
    return (
        "\n\n=== Standard View Daily Brief (보조 매크로 source) ===\n"
        f"{body}\n"
        "\n출처: ~/standardview backend (FastAPI + Gemini 2.5 Flash) —\n"
        "친구 라이선스 동의 코드 (StanLee5767/standardview) 활용. 매일\n"
        "08:00 KST 갱신. 위 brief 의 매크로 동향 / Market Moving Issues /\n"
        "4 comment cards 를 보조 perspective 로 활용 가능하지만 본 분석가의\n"
        "독립 판단이 우선. 동일 fact 가 본 instrument context 의 다른 source\n"
        "(macro 9-series / news / DART) 와 충돌 시 다른 source 의 정량값을\n"
        "우선 인용."
    )


def get_standardview_block() -> str:
    """One-call convenience helper: read latest brief + format. Empty
    string when unavailable. Used by build_instrument_context."""
    return format_for_macro_directive(get_standardview_brief())
